pipeline {
    agent any
    environment {
        dockerImage=''
        registry = 'keerthibattula/javaApp'
    }
    stages {
        // Building Docker images
    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build registry
        }
      }
    }
        
    }
}
