pipeline {
    agent any
    environment {
        dockerImage=''
        registry = 'keerthibattula/javaapp'
        registryCredential = 'dockerhub_id'
    }
    stages {
        // Building Docker images
    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build registry
        }
      }
    }
      stage('Upload Image') {
     steps{    
         script {
            docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
            }
        }
      }
    }  
       
         stage('Docker Run') {
     steps{
         script {
            dockerImage.run("-p 8096:5000 --rm --name javaappContainer")
         }
      }
    }
    }
}
