pipeline {
    agent any
    environment {
        dockerImage=''
        registry = 'kousalyag/javaapp'
        registryCredential = 'dockercrendentials'
    }
    stages {
        // Building Docker images
    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build registry
        }
      }
    }
      stage('Upload Image') {
     steps{    
         script {
            docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
            }
        }
      }
    }  
       
         
    }
}
